"""add user table and user_id fk to endpoints

Revision ID: 68fc9dca326e
Revises: e8bf0729867e
Create Date: 2026-09-17 18:24:55.705469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68fc9dca326e'
down_revision: Union[str, Sequence[str], None] = 'e8bf0729867e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('endpoints', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'endpoints', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'endpoints', type_='foreignkey')
    op.drop_column('endpoints', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
